
Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-j5nxh[0m
{"level":"warn","ts":1584600600.3700676,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600600.3703597,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-fdqcr[0m
{"level":"warn","ts":1584600600.865642,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584600600.8666034,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-environment-non-rhd87-9h4ws[0m
{"level":"warn","ts":1584600605.9054344,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600607.8493688,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/environment-non-prod-cluster-staging.git @ 0126be1aed5304779f52b6d76eba4664ac384f77 in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:0126be1aed5304779f52b6d76eba4664ac384f77,9:280d6b4d5b5c8b3804ea100e34702e26d22be871
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77:
DEBUG: ran git fetch --unshallow origin 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77
DEBUG: ran git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871
error: error during merge: merging 280d6b4d5b5c8b3804ea100e34702e26d22be871 into master: git output: Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871' command in directory '', output: 'Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-j5nxh[0m
{"level":"warn","ts":1584600600.3700676,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600600.3703597,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-fdqcr[0m
{"level":"warn","ts":1584600600.865642,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584600600.8666034,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-environment-non-rhd87-9h4ws[0m
{"level":"warn","ts":1584600605.9054344,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600607.8493688,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/environment-non-prod-cluster-staging.git @ 0126be1aed5304779f52b6d76eba4664ac384f77 in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:0126be1aed5304779f52b6d76eba4664ac384f77,9:280d6b4d5b5c8b3804ea100e34702e26d22be871
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77:
DEBUG: ran git fetch --unshallow origin 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77
DEBUG: ran git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871
error: error during merge: merging 280d6b4d5b5c8b3804ea100e34702e26d22be871 into master: git output: Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871' command in directory '', output: 'Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-j5nxh[0m
{"level":"warn","ts":1584600600.3700676,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600600.3703597,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-fdqcr[0m
{"level":"warn","ts":1584600600.865642,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584600600.8666034,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-environment-non-rhd87-9h4ws[0m
{"level":"warn","ts":1584600605.9054344,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584600607.8493688,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/environment-non-prod-cluster-staging.git @ 0126be1aed5304779f52b6d76eba4664ac384f77 in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-environment-non-rhd87-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:0126be1aed5304779f52b6d76eba4664ac384f77,9:280d6b4d5b5c8b3804ea100e34702e26d22be871
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77:
DEBUG: ran git fetch --unshallow origin 280d6b4d5b5c8b3804ea100e34702e26d22be871: 0126be1aed5304779f52b6d76eba4664ac384f77: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77
DEBUG: ran git reset --hard 0126be1aed5304779f52b6d76eba4664ac384f77 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871
error: error during merge: merging 280d6b4d5b5c8b3804ea100e34702e26d22be871 into master: git output: Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge 280d6b4d5b5c8b3804ea100e34702e26d22be871' command in directory '', output: 'Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m
