
Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-9xm7p[0m
{"level":"warn","ts":1584538740.2940216,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538740.2945907,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-nhkcz[0m
{"level":"warn","ts":1584538741.4429176,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584538741.447829,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-environment-non-8pqvf-l8l88[0m
{"level":"warn","ts":1584538746.6680663,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538748.6186597,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/environment-non-prod-cluster-staging.git @ 6140346a867baa0e707bb645a2ece6635ecb4bd6 in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:6140346a867baa0e707bb645a2ece6635ecb4bd6,5:af0465e10284502a1b4bd0b2c3e81dc148244ecf
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow af0465e10284502a1b4bd0b2c3e81dc148244ecf: 6140346a867baa0e707bb645a2ece6635ecb4bd6:
DEBUG: ran git fetch --unshallow origin af0465e10284502a1b4bd0b2c3e81dc148244ecf: 6140346a867baa0e707bb645a2ece6635ecb4bd6: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git reset --hard 6140346a867baa0e707bb645a2ece6635ecb4bd6
DEBUG: ran git reset --hard 6140346a867baa0e707bb645a2ece6635ecb4bd6 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge af0465e10284502a1b4bd0b2c3e81dc148244ecf
error: error during merge: merging af0465e10284502a1b4bd0b2c3e81dc148244ecf into master: git output: Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge af0465e10284502a1b4bd0b2c3e81dc148244ecf' command in directory '', output: 'Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-9xm7p[0m
{"level":"warn","ts":1584538740.2940216,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538740.2945907,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-nhkcz[0m
{"level":"warn","ts":1584538741.4429176,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584538741.447829,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-environment-non-8pqvf-l8l88[0m
{"level":"warn","ts":1584538746.6680663,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538748.6186597,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/environment-non-prod-cluster-staging.git @ 6140346a867baa0e707bb645a2ece6635ecb4bd6 in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-environment-non-8pqvf-2[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:6140346a867baa0e707bb645a2ece6635ecb4bd6,5:af0465e10284502a1b4bd0b2c3e81dc148244ecf
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow af0465e10284502a1b4bd0b2c3e81dc148244ecf: 6140346a867baa0e707bb645a2ece6635ecb4bd6:
DEBUG: ran git fetch --unshallow origin af0465e10284502a1b4bd0b2c3e81dc148244ecf: 6140346a867baa0e707bb645a2ece6635ecb4bd6: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git reset --hard 6140346a867baa0e707bb645a2ece6635ecb4bd6
DEBUG: ran git reset --hard 6140346a867baa0e707bb645a2ece6635ecb4bd6 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge af0465e10284502a1b4bd0b2c3e81dc148244ecf
error: error during merge: merging af0465e10284502a1b4bd0b2c3e81dc148244ecf into master: git output: Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge af0465e10284502a1b4bd0b2c3e81dc148244ecf' command in directory '', output: 'Auto-merging env/requirements.yaml
CONFLICT (content): Merge conflict in env/requirements.yaml
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m
